% This file provides the code for Tables 
%% Table 1 and Table 2 for design 1
addpath('../../4. simulation study/design 1 results/')
start_names_traces = 'sim_2tseed0sub';
sim_res_path = {strcat(start_names_traces, '20pairs100.mat'), strcat(start_names_traces, '20pairs400.mat'),  strcat(start_names_traces, '20pairs800.mat'), strcat(start_names_traces, '20pairs1000.mat'), strcat(start_names_traces, '20pairs1500.mat'),...
               strcat(start_names_traces, '50pairs100.mat'), strcat(start_names_traces, '50pairs400.mat'),  strcat(start_names_traces, '50pairs800.mat'), strcat(start_names_traces, '50pairs1000.mat'), strcat(start_names_traces, '50pairs1500.mat'),...
               strcat(start_names_traces, '100pairs100.mat'), strcat(start_names_traces, '100pairs400.mat'), strcat(start_names_traces, '100pairs800.mat'), strcat(start_names_traces, '100pairs1000.mat'), strcat(start_names_traces, '100pairs1500.mat')};
rng(0);
seq = 100:1000;
for i = 1:length(sim_res_path)
    sim_res{i} =  importdata(sim_res_path{i});
    n_subjects(i) =  sim_res{i}.gen_data_1.n_sub;
    n_pairs(i) =  sim_res{i}.gen_data_1.n_pairs;
    rand_theta1{i} =  rand(length(seq), size(sim_res{i}.results.phi_trace, 2));
    rand_theta2{i} =  rand(length(seq), size(sim_res{i}.results.phi_trace, 2));
end

tbl_theta1 = table(n_subjects', n_pairs',...
    coverage_theta1(sim_res, 0, 0, rand_theta1, seq),...
    coverage_theta1(sim_res, -0.01, 0, rand_theta1, seq),...
    coverage_theta1(sim_res, -0.02, 0, rand_theta1, seq),...
    coverage_theta1(sim_res, -0.04, 0, rand_theta1, seq),...
    coverage_theta1(sim_res, -0.01, -0.02, rand_theta1, seq),...
    coverage_theta1(sim_res, -0.02, -0.02, rand_theta1, seq),...
    coverage_theta1(sim_res, -0.04, -0.02, rand_theta1, seq),...
    length_theta1(sim_res, 0, rand_theta1, seq),...
    length_theta1(sim_res, -0.02, rand_theta1, seq),...
    'VariableNames', {'nsubjects', 'npairs',...
    'coveragemar', 'mnarmar1', 'mnarmar2', 'mnarmar3',...
    'mnarmanr1', 'mnarmnar2', 'mnarmnar3', 'lengthmar', 'lengthmnar'});
writetable(tbl_theta1, 'Tables.xlsx', 'Sheet', 'theta1_design1')

tbl_theta2 =  table(n_subjects', n_pairs',...
    coverage_theta2(sim_res, 0, 0, rand_theta2, seq),...
    coverage_theta2(sim_res, 0.02, 0, rand_theta2, seq),...
    coverage_theta2(sim_res, 0.04, 0, rand_theta2, seq),...
    coverage_theta2(sim_res, 0.05, 0, rand_theta2, seq),...
    coverage_theta2(sim_res, 0.02, 0.04, rand_theta2, seq),...
    coverage_theta2(sim_res, 0.04, 0.04, rand_theta2, seq),...
    coverage_theta2(sim_res, 0.05, 0.04, rand_theta2, seq),...
    length_theta2(sim_res, 0, rand_theta2, seq),...
    length_theta2(sim_res, 0.04, rand_theta2, seq),...
    'VariableNames', {'nsubjects', 'npairs',...
    'coveragemar', 'mnarmar1', 'mnarmar2', 'mnarmar3',...
    'mnarmnar1', 'mnarmnar2', 'mnarmnar3', 'lengthmar', 'lengthmnar'});
writetable(tbl_theta2, 'Tables.xlsx', 'Sheet', 'theta2_design1')

%% Table 3 and Table 4 for design 2
addpath('../../4. simulation study/design 1 results/')
start_names_traces = 'sim_2trealseed0sub';
sim_res_path={strcat(start_names_traces, '20pairs500.mat'), strcat(start_names_traces, '20pairs1000.mat'),  strcat(start_names_traces, '20pairs1500.mat'), strcat(start_names_traces, '20pairs2000.mat'), strcat(start_names_traces, '20pairs3000.mat'), strcat(start_names_traces, '20pairs5000.mat'), strcat(start_names_traces, '20pairs10000.mat'),...
              strcat(start_names_traces, '50pairs500.mat'), strcat(start_names_traces, '50pairs1000.mat'),  strcat(start_names_traces, '50pairs1500.mat'), strcat(start_names_traces, '50pairs2000.mat'), strcat(start_names_traces, '50pairs3000.mat'), strcat(start_names_traces, '50pairs5000.mat'), strcat(start_names_traces, '50pairs10000.mat'),...
              strcat(start_names_traces, '100pairs500.mat'), strcat(start_names_traces, '100pairs1000.mat'),  strcat(start_names_traces, '100pairs1500.mat'), strcat(start_names_traces, '100pairs2000.mat'), strcat(start_names_traces, '100pairs3000.mat'), strcat(start_names_traces, '100pairs5000.mat'), strcat(start_names_traces, '100pairs10000.mat')};

rng(1077281);
seq=3000:5:6000;

for i = 1:length(sim_res_path)
    sim_res{i} =  importdata(sim_res_path{i});
    n_subjects(i) =  sim_res{i}.gen_data_1.n_sub;
    n_pairs(i) =  sim_res{i}.gen_data_1.n_pairs;
    rand_theta1{i} =  rand(length(seq), size(sim_res{i}.results.phi_trace,2));
    rand_theta2{i} =  rand(length(seq), size(sim_res{i}.results.phi_trace,2));
end

tbl_theta1 = table(n_subjects', n_pairs',...
    coverage_theta1(sim_res, 0, 0, rand_theta1, seq),...
    coverage_theta1(sim_res, -0.01, 0, rand_theta1, seq),...
    coverage_theta1(sim_res, -0.02, 0, rand_theta1, seq),...
    coverage_theta1(sim_res, -0.04, 0, rand_theta1, seq),...
    coverage_theta1(sim_res, -0.01, -0.02, rand_theta1, seq),...
    coverage_theta1(sim_res, -0.02, -0.02, rand_theta1, seq),...
    coverage_theta1(sim_res, -0.04, -0.02, rand_theta1, seq),...
    length_theta1(sim_res, 0, rand_theta1, seq),...
    length_theta1(sim_res, -0.02, rand_theta1, seq),...
    'VariableNames', {'nsubjects','npairs',...
    'coveragemar', 'mnarmar1', 'mnarmar2', 'mnarmar3',...
    'mnarmanr1', 'mnarmnar2', 'mnarmnar3', 'lengthmar', 'lengthmnar'});
writetable(tbl_theta1, 'Tables.xlsx', 'Sheet', 'theta1_design2')

tbl_theta2 =  table(n_subjects', n_pairs',...
    coverage_theta2(sim_res, 0, 0, rand_theta2, seq),...
    coverage_theta2(sim_res, 0.02, 0, rand_theta2, seq),...
    coverage_theta2(sim_res, 0.04, 0, rand_theta2, seq),...
    coverage_theta2(sim_res, 0.05, 0, rand_theta2, seq),...
    coverage_theta2(sim_res, 0.02, 0.04, rand_theta2, seq),...
    coverage_theta2(sim_res, 0.04, 0.04, rand_theta2, seq),...
    coverage_theta2(sim_res, 0.05, 0.04, rand_theta2, seq),...
    length_theta2(sim_res, 0, rand_theta2, seq),...
    length_theta2(sim_res, -0.01, rand_theta2, seq),...
    'VariableNames', {'nsubjects', 'npairs',...
    'coveragemar', 'mnarmar1', 'mnarmar2', 'mnarmar3',...
    'mnarmnar1', 'mnarmnar2', 'mnarmnar3', 'lengthmar', 'lengthmnar'});
writetable(tbl_theta2, 'Tables.xlsx', 'Sheet', 'theta2_design2')

